manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: encoder-fix
      url-base: https://github.com/andre-tm-hui
  projects:
    - name: zmk
      remote: encoder-fix
      revision: sofle
      import: app/west.yml
  self:
    path: config
