manifest:
  remotes:
    - name: MangoIV
      url-base: https://github.com/MangoIV
  projects:
    - name: zmk
      remote: MangoIV
      revision: draculad
      import: app/west.yml
  self:
    path: config
